### ISSUE TITLE
Problem With 1-dimensional Data

### ISSUE THREAD

**Issue by ali63843123123** [zrmacc/MGMM#1]
Hi :),
FitGMM breaks when it tries to work with 1-dimensional data (I'm not sure why but I'm guessing the problem stems from [here](https://github.com/zrmacc/MGMM/blob/master/R/06_Mix_MVN.R#L556); if input data is 1-D, "out" would be having only one row, and that indexing would drop the extra dimensions and turn "out" into a vector, which will be problematic on the next line where you're assigning rownames to it)

Thanks in advance, and thanks for the package it's awesome!

**Comment by zrmacc** [comment]
Thanks so much for identifying this issue and pointing directly to the cause. This has been corrected in the updated version (1.0.1). Please let me know if you encounter any additional difficulties.
