### ISSUE TITLE
Cannot Initialize if no observations are complete

### ISSUE THREAD

**Issue by zhangtj1996** [zrmacc/MGMM#2]
Hi there, thanks for the wonderful package.

I met the following error when dealing with some real data. “If no observations are complete, initial values are required for all parameters.”

I understand this part has not been developed, but having such data in real life is quite common. Any solutions or future plans for the initialization?

**Comment by zrmacc** [comment]
Hello,

Thanks for your interest in the package. When complete cases are available, model parameters are initialized by running k-means clustering on the complete cases, then estimating the cluster means, covariances, and proportions. Lacking complete cases, it is unclear how to perform the initial clustering. In addition, whether an approach is appropriate (e.g. performing an initial imputation, then clustering, then initializing...) will likely depend on the specific data set. For these reasons, there is not currently a plan to provide an initialization in the absence of complete cases. If there is an approach you'd like to suggest, I will be happy to consider it.
