### ISSUE TITLE
FitGMM fails if the number of observations is not large enough

### ISSUE THREAD

**Issue by frederikziebell** [zrmacc/MGMM#3]
If `n <= d`, `FitGMM()` gives an _Initial covariance matrices are not all positive definite_ error:

```r

set.seed(1)

n <- 30
d <- 30
mat <- rbind(
  matrix(rnorm(n*d), nrow = n),
  matrix(rnorm(n*d, mean = 1), nrow = n)
)
FitGMM(mat, k = 2)
```

and I even found an example with `n > d`, where `FitGMM` fails with _chol(): decomposition failed_ :

```r
set.seed(1)

n <- 23
d <- 22
mat <- rbind(
  matrix(rnorm(n*d), nrow = n),
  matrix(rnorm(n*d, mean = 1), nrow = n)
)
FitGMM(mat, k = 2)
```

I think the issue is that the internally computed covariance matrices (e.g. inside `MixInit()`) are ill-conditioned in the sense that they are positive definite but some eigenvalues are very close to zero. This leads to down-stream issues when the `mvnfast` package is called, which attempts but fails to compute a Cholesky decomposition. A better approach would be use the `mvtnorm` package, which uses the slower but more numerically stable SVD instead. As per [this discussion](https://stackoverflow.com/questions/29615440/one-of-eigenvalues-of-covariance-matrix-is-negative-in-r), it could also be possible to approximate covariance matrices by better conditioned ones via `Matrix::nearPD` before using `mvnfast`, but this would counteract the desired speed gain.

You could also have a look at the `pdMat` class of the `nlme` package, which contains a lot of linear algebra routines related to positive definite matrices, e.g. `nlme::logDet()`, which you use inside `MixEMObj()`.

**Comment by zrmacc** [comment]
Hello,

Thanks for your interest in the package. I think the problem runs deeper than just the initialization. When $n < d$, the model being fit has more parameters than there are data points, so the maximum likelihood solution is not identified. To assist with the positive definiteness issue you're encountering, [v1.0.1.2](https://github.com/zrmacc/MGMM/releases/tag/v1.0.1.2) introduces a new ridge parameter $\lambda$. When $\lambda > 0$, a positive constant proportional to $\lambda$ is added to the diagonals of all covariance matrices during initialization and estimation: $\Sigma_{k} \mapsto \Sigma_{k} + (\lambda/n_{k})I$. You can experiment with different amounts of regularization in your setting, for example:
```
set.seed(1)

n <- 30
d <- 30
mat <- rbind(
  matrix(rnorm(n*d), nrow = n),
  matrix(rnorm(n*d, mean = 1), nrow = n)
)
FitGMM(mat, k = 2, lambda = 1e-3)
```
Note that this may not be a perfect solution (a model with fewer free parameters may be needed for the $n \lesssim d$ setting), but hope it helps.

**Comment by frederikziebell** [comment]
Thanks, I'll give it a try. In my application (RNA-seq data), $n\approx 1000$ and $d\approx 20000$. Is it possible that $\lambda$ could be chosen via [cross-validation as implemented in glmnet](https://glmnet.stanford.edu/reference/cv.glmnet.html)?

**Comment by frederikziebell** [comment]
It seems there are still issues, because even for $n > d$ and even with a very large ridge-penalty,  I an error of a failed Cholesky decomposition:

```r
set.seed(1)

n <- 2000
d <- 1000
mat <- rbind(
  matrix(rnorm(n*d), nrow = n),
  matrix(rnorm(n*d, mean = 1), nrow = n)
)
FitGMM(mat, k = 2, lambda = 10)
```

**Comment by zrmacc** [comment]
Yes, ideally $\lambda$ would be chosen via cross-validation. It's important to keep in mind that `MGMM` estimates unstructured covariance matrices, which have $d + \binom{d}{2} = d(d+1)/2$ parameters per cluster. For the applications you are contemplating, I think you either need to reduce the dimensionality (e.g. remove low variance and highly correlated genes, then apply PCA) or impose structure on the covariance matrix (e.g. block diagonal with a single off-diagonal term per block), perhaps both. The latter option is a non-trivial extension of the current package and is not planned at this time.
